### ISSUE TITLE
how to choose grid divisons in run flux analysis option?

### ISSUE THREAD

**Issue by AditiiiGarg** [iat-cener/tonatiuh#116]
In Tonatiuh, there is an option of run flux analysis, which gives total power absorbed by the receiver along with maximum, minimum, and average flux values. Besides, it also provides a flux profile along the circumference and length of the cylindrical absorber with coordinates.
My query is that there is an option for grid divisions in run flux analysis and changing the grid divisions impacts the maximum flux value. So how should I decide which grid divisions to choose?
I have attached the two figures for grid division of 20 x 20 where max. flux is 5676.8 W/sq.m   and 200 x 20 where the max flux is 19905.1 W/sq.m. 
Also, can anyone suggest any technique to develop an expression for flux as a function of the angle around the absorber circumference? ( I have tried using excel that creates a flux equation best fit as a polynomial of 6th order for angles ranging from 0-360 degree)

![20 x 20](https://user-images.githubusercontent.com/104768070/176630259-f30d9df1-6aed-44a8-a2e6-aede5732ad2f.JPG)
![200 x 20](https://user-images.githubusercontent.com/104768070/176630328-a9cbd617-15d7-495a-baca-693d9ce7024a.JPG)

**Comment by amutuberria** [comment]
The discretization that you should define is completely related to the application and, above all, to the needed precision of your results.
It makes sense by changing the number of cells that you are defining to the grid the maximum flux value changes since this value is the highest value between the cells. If we suppose only a single cell, it would cover the entire surface and therefore the maximum flux would be equal to the average flux.
Make sure that when you choose the appropriate number of cells, to run all the required number of rays to obtain fully converged solution.

**Comment by AditiiiGarg** [comment]
Thank you amutuberria
