### ISSUE TITLE
Radiation losses

### ISSUE THREAD

**Issue by LouizaRBH** [iat-cener/tonatiuh#98]
Hi everybody.
I used Tonatiuh in my study. Mathematica was generated for post processing binary files and finally temperature distribution was simulated using Comsol. I considered that my receiver is under vaccum so convection and conduction are not considered but thermal radiation is there. I think that absorbed radiation is considered by Tonatiuh since it's the interaction between photons and the receiver but can i say that emitted radiation is also taken in consideration or i have to treat it after using Comsol and finding the surface temperature of material?
I hope I have made my question clear and thank you in advance for your responses.

**Comment by mahmoudalaaeldeen** [comment]
Dear
Tonatiuh takes into account reflection losses (due to the reflectivity of the absorber material).  However, during the conjugate heat transfer simulation, using comsol or any other software, you should employ radiative losses because these losses are a function of absorber temperature. And Tonatiuh did not consider them.



[cid:image001.png@01D3F510.8D15BBD0]Best regards,
Mahmoud Alaa | Research & Teaching Assistant
Faculty of Engineering, Helwan University
11792, 1 sherif street, Helwan, Cairo, Egypt
Cell phone: +(2) 010 69979918
mahmoud.alaa@h-eng.helwan.edu.eg<mailto:mahmoud.alaa@h-eng.helwan.edu.eg>

**Comment by ilescener** [comment]
Dear LouizaRBH,

As mahmoudalaaeldeen has said and giving a further explanation. Tonatiuh provides only the optical behaviour of your system. This means that it is possible to simulate the incident power into any surface usually in terms of its density flux map (W/m^2) which is later the required input in the thermal simulation, in your case Comsol.

Kind regards
Iñigo

**Comment by LouizaRBH** [comment]
Thank you very much. the idea became clear to me.
Best regards.
